chore: validation in FormInput component finished
AlanPinhon/age-calculator-app-ts pull request #2
Opened 2023-08-17 19:39 UTC by AlanPinhon

Es una validación en los inputs mediante expresiones regulares

2023-08-17 19:45 UTC, gonzalo-novak approved these changes

2023-08-17 19:45 UTC, gonzalo-novak commented on src/components/FormInput.tsx
> +    if(labelId === 'Day') regexValidator = /^(0?[1-9]|[12][0-9]|3[01])$/;
Tal vez sea bueno dejar algún comment sobre qué hace cada validación. A veces es complicado entender expresiones regulares en primer instancia

2023-08-17 19:45 UTC, gonzalo-novak commented on src/components/FormInput.tsx
> +      {!isValid && <p className="msg-error">This field is required</p>}
Sugerencia: Podrías dejar las validaciones fuera de este componente. El componente no debería estar atado a validaciones. Sólo debería recibir por props el mensaje de error en caso de que exista. Sin embargo, eso se puede considerar en la parte de refactorización ;)

2023-08-17 19:50 UTC, AlanPinhon commented on src/components/FormInput.tsx
> +    if(labelId === 'Day') regexValidator = /^(0?[1-9]|[12][0-9]|3[01])$/;
De acuerdo, pondré un comentario para que sea más claro.

2023-08-18 00:28 UTC, gonzalo-novak requested changes

2023-08-18 00:28 UTC, gonzalo-novak commented on src/components/FormCalculator.tsx
> +    setDate( oldDate => ({ ...oldDate, [property]: value } as TDate) );
Normalemente el código debería hablar por sí mismo. Adicionalmente, siempre es sugerido escribir los comentarios en Inglés para tener consistencia. 🐤

2023-08-18 00:28 UTC, gonzalo-novak commented on src/components/FormCalculator.tsx
> +    //Asigna la expresión regular de acuerdo a la propiedad del input.
Yo me refería en poner comentarios a los regex para entender cuál es la validación que hacen. Aquí un ejemplo (igual lo puedes usar):

```tsx
if(property === 'day') {
    // Matches numbers 01-31, leading 0 is optional
    regexValidator = /^(0?[1-9]|[12][0-9]|3[01])$/;
}
if(property === 'month') {
    // Matches numbers 01-12, leading 0 is optional
    regexValidator = /^(0?[1-9]|1[0-2])$/;
}
if(property === 'year') {
    // Matches 1 to 4 digits for year
    regexValidator = /^\d{1,4}$/;
}
```

2023-08-18 00:28 UTC, gonzalo-novak commented on src/components/FormCalculator.tsx
> +      {errors.month && <p className="msg-error">Must be a valid month</p>}
El FormInput podría tomar el mensaje de error y dentro del mismo componente poner ese mensaje. Recuerda, si tienes  que repetir algo más de 2 veces, entonces será mejor pensar una manera de cómo abstraer eso que estas repitiendo. 🥇 

```tsx
<FormInput
  placeholderText="MM"
  labelId="Month"
  setInputValue={...}
  error={error.month}
 >
 ```

Dentro de tu componente, sólo revisas si el string es diferente a vació para mostrar dicho error:

```tsx
// FormInput.tsx

const FormInput = ({ error, ...rest }) => {
 ... all your code
{ error && <p>{error}</p>}
}
```

2023-08-18 01:09 UTC, AlanPinhon commented on src/components/FormCalculator.tsx
> +    //Asigna la expresión regular de acuerdo a la propiedad del input.
Entendido. Actualizo entonces los comentarios para los regex. 🐤

2023-08-18 02:26 UTC, gonzalo-novak requested changes

2023-08-18 02:26 UTC, gonzalo-novak commented on src/components/FormInput.tsx
> +      {error && <p className="msg-error">Must be a valid {labelId.toLowerCase()}</p>}
Sugiero que inyectes el error en la etiqueta `<p>` en vez de inyectar el `labelId`. 👀 

```tsx
{error && <p className="msg-error">{error}</p>}
```

Dicha prop te va a dar la flexibilidad para escribir los otros errores de validación. Si hardcodeas el mensaje 
`Must be a valid`, ¿qué pasará si yo al error le mando el string de "El año es mayor al actual"? 

El resultado sería: 

"Must be a valid El año es mayor al actual"

2023-08-18 02:26 UTC, gonzalo-novak commented on src/components/FormInput.tsx
> +  error:boolean
El error debería ser un string

2023-08-18 02:32 UTC, gonzalo-novak commented on src/components/FormCalculator.tsx
> +    if(property === 'day') regexValidator = /^(0?[1-9]|[12][0-9]|3[01])$/; // Matches numbers 01-31, leading 0 is optional
El método test retorna un booleano, por ende si retorna un false con base al regex que le envías, podrías mandar el string del error a mostrar:

```tsx
if(property === 'day'){
      // Matches numbers 01-31, leading 0 is optional
      (/^(0?[1-9]|[12][0-9]|3[01])$/.test(value)) && setError((currentError) => ({...curentError, day: "El día no coincide dentro del rango bla bla bla"}))
      
      // Puedes hacer lo mismo de arriba pero para otras validaciones ☝🏻 
}

```

2023-08-18 04:30 UTC, AlanPinhon commented on src/components/FormCalculator.tsx
> +    if(property === 'day') regexValidator = /^(0?[1-9]|[12][0-9]|3[01])$/; // Matches numbers 01-31, leading 0 is optional
Realizando la corrección, si bien marca el error al ingresar un valor incorrecto, después de ingresar el valor correcto el error no desaparece. 

Realicé el siguiente cambio para que se muestre y oculte el mensaje:

`if(property === 'day') {
      // Matches numbers 01-31, leading 0 is optional
      const isValidDay = /^(0?[1-9]|[12][0-9]|3[01])$/.test(value);
      setErrors( prevError => ( {...prevError, day: !isValidDay ? 'Must be a valid day' : ''} ) );
    }`

De todos modos cualquier otra sugerencia es tomada en cuenta. 🤓

2023-08-18 05:29 UTC, gonzalo-novak commented on src/components/FormCalculator.tsx
> +    }
¡Bien! Ahí dentro de las condicionales puedes meter las otras validaciones, por ejemplo, cuando el año es mayor al actual, etc. 👏🏻

2023-08-19 01:13 UTC, gonzalo-novak approved these changes

2023-08-24 21:56 UTC, AlanPinhon commented on src/components/FormCalculator.tsx
> +    }
Se han hecho las validaciones de fechas futuras en la parte de la función `handleCalculateAge` ya una vez que se validan las fechas mediante expresiones regulares y se muestran los errores. 🤓

2023-08-25 15:44 UTC, gonzalo-novak requested changes
¡Buen trabajo! El hecho de que hayas desacoplado la lógica en otros archivos hace de tu archivo principal más legible. Sólo deje una recomendación. 👏🏻

2023-08-25 15:44 UTC, gonzalo-novak commented on src/components/FormCalculator.tsx
> +    if(property === 'year') validateDate(value, /^\d{1,4}$/, 'Must be a valid year'); //RegEx matches 1 to 4 digits for year
Si le pones el año en plan "98" en vez de "1998" me deja pasar. Desconozco si sea la funcionalidad esperada pero el resultado es el mismo para la clase `Date`. Sin embargo, si pones algo como "123" en el año, puede que te de resultados no esperados. Por ende, recomiendo que el regex siempre valide que hayan 4 caracteres para el año.

```suggestion
    if(property === 'year') validateDate(value, /^\d{4}$/, 'The year must have four characters');
```

2023-08-25 19:14 UTC, AlanPinhon commented on src/components/FormCalculator.tsx
> +    if(property === 'year') validateDate(value, /^\d{1,4}$/, 'Must be a valid year'); //RegEx matches 1 to 4 digits for year
No había notado ese detalle. Quedó ya solucionado y todas las validaciones se han movido al momento de dar clic y mostrar los errores de esa forma.

2023-08-26 03:44 UTC, gonzalo-novak requested changes
¡Lo lograste! Buen trabajo bro 🎉 

Sólo recomiendo que cambies el mensaje de error cuando el año no es correcto. Tal vez podrías poner que el año requiere tener 4 caracteres. Adicionalmente puedes poner un ejemplo:

"The year must have 4 characters (e.g. 1998.)"

2023-08-26 03:44 UTC, gonzalo-novak commented on src/components/FormResult.tsx
> +export const FormResult = ({ageResults}:resultsProps) => {
Solo procura poner espacios cuando vayas a destructurar tus props. A veces hay devs algo pickys en ese tema. 
```suggestion
export const FormResult = ({ ageResults }: resultsProps) => {
```

2023-08-28 19:02 UTC, merged