feat: first test
AlanPinhon/age-calculator-app-ts pull request #3
Opened 2023-08-28 22:40 UTC by AlanPinhon

Primeros test en la aplicación

2023-08-28 22:57 UTC, gonzalo-novak commented on test/firstTest.test.tsx
> +  expect(1+1).toEqual(2);
El ejemplo podría ser usando testing library para saber si tu entorno de testing está al %100. No recuerdo si vitest ya tiene integrado testing library o hay que integrarlo

2023-08-28 23:01 UTC, gonzalo-novak commented on test/firstTest.test.tsx
> +  expect(1+1).toEqual(2);
@AlanPinhon Aquí hay un articulo donde te dice como integrar testing library

https://www.robinwieruch.de/vitest-react-testing-library/

2023-08-28 23:17 UTC, AlanPinhon commented on test/firstTest.test.tsx
> +  expect(1+1).toEqual(2);
Justo es lo que estoy viendo en la config de vitest con la parte del coverage.

2023-08-31 05:35 UTC, gonzalo-novak requested changes

2023-08-31 05:35 UTC, gonzalo-novak commented on coverage/FormInput.tsx.html
> +<!doctype html>
Ups! Normalmente no se sube el folder de coverage. Añade dicho folder en el .gitignore y tal vez necesites hacer lo siguiente para eliminar dicho folder en github: 

```bash
# Remove folder from git tracking
git rm -r --cached coverage/

# Add the folder to .gitignore
echo "coverage/" >> .gitignore

# Commit changes
git add .gitignore
git commit -m "Untrack and ignore coverage"

# Push to GitHub
git push origin first-test --force

```

2023-08-31 17:55 UTC, AlanPinhon commented on coverage/FormInput.tsx.html
> +<!doctype html>
Entendido. El folder ya ha sido eliminado en github.

2023-08-31 18:43 UTC, gonzalo-novak requested changes

2023-08-31 18:43 UTC, gonzalo-novak commented on .gitignore
No se puede ver aquí en el diff pero veo que el exclusión del directorio coverage está con un espacio en plan:

c o v e r a g e /

Debería ir sin espacios 🐦

2023-08-31 18:50 UTC, AlanPinhon commented on .gitignore
No me percaté de eso. De hecho esos espacios estaban con un cuadro rojo con el texto "HTML", pero ya está actualizado. 🐤

2023-08-31 19:06 UTC, gonzalo-novak requested changes

2023-08-31 19:06 UTC, gonzalo-novak commented on test/components/FormInput.spec.tsx
> +    screen.debug();
Una vez que tu test haya cumplido con las expectativas, se debería quitar el debug() 🛩️

2023-08-31 19:34 UTC, gonzalo-novak approved these changes
Todo bien. Sólo dejé algo que puedes hacer opcionalmente. Si no, ya puedes darle merge y continuar con tus test en otra nueva rama

2023-08-31 19:34 UTC, gonzalo-novak commented on test/components/FormInput.spec.tsx
> +        setInputValue={setInputValueMock}
También podrias revisar si el valor que te manda el setInputValue es el esperado ;D

2023-09-01 00:05 UTC, gonzalo-novak approved these changes

2023-09-01 00:10 UTC, merged