test: first test in FormCalculator
AlanPinhon/age-calculator-app-ts pull request #4
Opened 2023-09-01 05:17 UTC by AlanPinhon

Tests realizados en el componente FormCalculator

2023-09-01 05:52 UTC, gonzalo-novak reviewed
¡Bien! Adicionalmente podrías pobrar cuando un input está vacío. Tengo entendido que sólo es esa validación la que está ahí. De ser que no esté, me imagino que nada más deberías probar que lo que escribas sí se vea reflejado en el .value 💡

2023-09-03 18:21 UTC, gonzalo-novak approved these changes

2023-09-04 19:58 UTC, gonzalo-novak requested changes

2023-09-04 19:58 UTC, gonzalo-novak commented on test/components/FormCalculator.spec.tsx
> +    render(<FormCalculator setAgeResults={setAgeResultsMock}/>)
Sugeriría que el `setAgeResultsMock` lo pongas dentro de cada test porque te podrían dar falsos positivos en caso de que ese mock haya sido llamado anteriormente en otro test. 🧷

2023-09-04 19:58 UTC, gonzalo-novak commented on test/components/FormCalculator.spec.tsx
> +    expect(setAgeResultsMock).toHaveBeenCalledTimes(1);
Sería bueno probar que los valores que introduciste (22/5/1992) sean lo que se esperan 🦆 

Hay un método para hacer eso, creo que se llama `toHaveBeenCalledWith`

2023-09-05 03:06 UTC, gonzalo-novak reviewed
Lo veo bien por ahora! ⚽

2023-09-06 04:11 UTC, gonzalo-novak approved these changes

2023-09-07 04:26 UTC, gonzalo-novak approved these changes
Si le das merge a este PR, asegurate de actualizar el otro branch que abriste con estos cambios

2023-09-07 17:00 UTC, AlanPinhon commented
Vale. Entonces le doy merge y voy a actualizar la otra rama. 🐤

2023-09-07 17:32 UTC, merged